#
# Copyright (C) 2025-26 https://github.com/dizaumuna - All rights reserved.
#
#

# ================================ Configurations ================================

DEVICE_MANUFACTURER="samsung"      #   Device manufacturer (ensure this matches your device)
DEVICE_CODE="a15,a15x,a15k"        #   Device codename (ensure this matches your device)
ONEUI_VERSION="8.0"
KERNEL_NAME="Floha Kernel+"
DEVICE_MODEL="SM-A155F, SM-A156F, SM-A156B"


# ============================== Configurations End ==============================